name: Push Issues

on:
  push:
    tags:
      - '*-issues'

jobs:
  IssuesPre:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: tag-name
        id: tag
        run: |
          tag="${{github.ref}}"
          [[ $tag == refs/tags/* ]] && tag="${tag#refs/tags/}" || false
          echo "$tag"
          echo "::set-output name=tagName::$tag"
          sudo apt install -y python3-pycurl || ( sleep 60s && sudo apt install -y python3-pycurl ) || ( sleep 60s && sudo apt install -y python3-pycurl )
      - name: Update Tag
        run: |
          ISSUES_REPO="ElonH/testAction"
          [[ ${{steps.tag.outputs.tagName}} =~ ctcgfw* ]] && ISSUES_REPO="project-openwrt/openwrt-isco"
          [[ ${{steps.tag.outputs.tagName}} =~ latest* ]] && ISSUES_REPO="project-openwrt/openwrt-latest-isco"
          echo "issues repo: $ISSUES_REPO"
          ./scripts/issues-push -i issues.json -ipo "$ISSUES_REPO" -u "${{github.actor}}" -t "${{secrets.GITHUB_TOKEN}}" || true
          # git push -d "https://${{github.actor}}:${{secrets.RELEASE_TOKEN}}@github.com/${{github.repository}}.git" ${{steps.tag.outputs.tagName}}
